# Generated by Django 2.2.16 on 2022-04-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "user"),
                    ("admin", "admin"),
                    ("moderator", "moderator"),
                ],
                max_length=100,
            ),
        ),
    ]
